# Generated by Django 5.1 on 2024-08-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aluna', '0002_aluno_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('titulo', models.CharField(max_length=100, null=True)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
