# Generated by Django 5.1 on 2024-08-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aluna', '0003_sobre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
