# Generated by Django 5.1 on 2024-08-31 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aluna', '0005_convidados_casamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casamento',
            name='convidados',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aluna.convidados'),
        ),
    ]
